"""delete phone from user table

Revision ID: 780bdf77bbf7
Revises: 84d301477097
Create Date: 2022-05-21 16:26:48.387430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780bdf77bbf7'
down_revision = '84d301477097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
